global:
  scrape_interval: 10s
  evaluation_interval: 10s

  external_labels:
    monitor: django-monitor

rule_files:
  - "django.rules"

scrape_configs:
  - job_name: "django"
    static_configs:
      - targets: ["127.0.0.1:8000", "backend:8000"]
