apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wellplay.fullname" . }}
  labels:
    {{- include "wellplay.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "wellplay.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wellplay.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.image.imagePullSecrets }}
      containers:
        - name: {{ include "wellplay.fullname" . }}
          image: {{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort.react }}
