apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellplay.fullname" . }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $val := .Values.secret.django }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellplay.db.fullname" . }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $val := .Values.secret.db }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
