apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.lb.type }}
  selector:
    {{- include "wellplay.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.lb.port }}
      targetPort: {{ .Values.containerPort.django }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-nodeport
spec:
  type: {{ .Values.service.db.type }}
  selector:
    {{- include "db.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.db.port }}
      targetPort: {{ .Values.containerPort.db }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-nodeport
spec:
  type: {{ .Values.service.redis.type }}
  selector:
    {{- include "redis.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.redis.port }}
      targetPort: {{ .Values.containerPort.redis }}