apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellplay.fullname" . }}
type: {{ .Values.secret.type }}
data:
  DJANGO_SECRET_KEY: {{ .Values.secret.django.DJANGO_SECRET_KEY | b64enc | quote }}


---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wellplay.db.fullname" . }}
type: {{ .Values.secret.type }}
data:
  {{- range $key, $val := .Values.secret.db }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
