FROM python:3.11-alpine

ARG APP_HOME=/backend

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

RUN mkdir ${APP_HOME}
WORKDIR ${APP_HOME}

# install requirements
COPY ./requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# copy all
COPY . ${APP_HOME}

# celery -A config worker -l info
CMD [ "celery", "-A", "config", "worker", "-l", "info" ]
