#!/bin/sh

python manage.py collectstatic --no-input

python manage.py makemigrations
python manage.py migrate

celery -A config worker -l info &

gunicorn config.wsgi:application --config config/gunicorn_config.py
