name: CI-front

on:
  push:
    tags:
      - "*.*.*"

env:
  IMAGE: ${{ vars.NCP_REGISTRY }}/wp-frontend
  IMAGE_TAG: ${{ vars.NCP_REGISTRY }}/wp-frontend:latest

jobs:
  build-push:
    name: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.NCP_REGISTRY }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Get current timestamp
        id: timestamp
        run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

      - name: add env
        id: env
        run: |
          cd frontend/wp-front-app
          touch .env
          echo "REACT_APP_API_URL=${{ secrets.BACKEND_LB }}" >> .env

      - name: bulid and push refs/heads
        if: startsWith(github.ref, 'refs/heads')
        uses: docker/build-push-action@v4
        with:
          context: frontend/wp-front-app
          tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
          push: true

      - name: bulid and push refs/tags
        if: startsWith(github.ref, 'refs/tags')
        uses: docker/build-push-action@v4
        with:
          context: frontend/wp-front-app
          tags: ${{ env.IMAGE_TAG }},"${{ env.IMAGE }}:${{ github.ref_name }}"
          push: true
